import React, { createContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export { LanguageContext };

// Translations object (imported from original implementation)
const translations = {
  en: {
    // App
    'app.title': 'Hotel Inventory',
    'app.subtitle': 'Management System',
    'app.loading': 'Loading inventory system...',
    'app.version': __APP_VERSION__,
    'app.accessDenied': 'Access Denied',
    'app.noPermission': 'You do not have permission to access this page.',
    'app.maintenance.title': 'System Under Maintenance',
    'app.maintenance.message': 'The system is currently under maintenance. Please try again later.',
    'app.maintenance.contact': 'If you need immediate assistance, please contact the system administrator.',

    // Menu
    // Login & Auth
    'login.title': 'Hotel Inventory Management System',
    'login.subtitle': 'Delonix Group',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.error': 'Invalid username or password',
    'login.logout': 'Logout',
    'login.welcome': 'Welcome',
    'login.forceChange': 'You must change your password before continuing',
    'login.newPassword': 'New Password',
    'login.confirmNewPassword': 'Confirm New Password',
    'login.changeAndContinue': 'Change Password & Continue',
    'login.passwordChanged': 'Password changed successfully',
    'login.passwordMismatch': 'Passwords do not match',
    'login.passwordShort': 'Password must be at least 6 characters',

    'menu.dashboard': 'Dashboard',
    'menu.items': 'Master Items',
    'menu.categories': 'Item Categories',
    'menu.vendors': 'Vendors',
    'menu.departments': 'Departments',
    'menu.warehouses': 'Warehouses',
    'menu.stock': 'Stock Balance',
    'menu.movements': 'Bin Card',
    'menu.pr': 'Purchase Request',
    'menu.po': 'Purchase Order',
    'menu.opname': 'Stock Opname',
    'menu.writeoff': 'Write-Off',
    'menu.pi': 'Purchase Invoice',
    'menu.reports': 'Reports',
    'menu.userMgmt': 'User Management',
    'menu.roleMgmt': 'Role Management',
    'menu.changePassword': 'Change Password',
    'menu.group.globalMaster': 'Global Master',
    'menu.group.hotelMaster': 'Hotel Master',
    'menu.group.purchase': 'Purchase Management',
    'menu.group.stockIn': 'Stock In',
    'menu.group.stockOut': 'Stock Out',
    'menu.group.stock': 'Stock Management',
    'menu.group.settings': 'Settings',
    'menu.roomMakeupNew': 'Room Make Up',
    'menu.transfer': 'Transfer',
    'menu.directPurchase': 'Direct Purchase',
    'menu.hotels': 'Hotels',

    // Hotels Page
    'hotels.title': 'Hotel Profile',
    'hotels.companyName': 'Company Name (PT)',
    'hotels.npwp': 'NPWP',
    'hotels.hotelName': 'Hotel Name',
    'hotels.hotelCode': 'Hotel Code',
    'hotels.address': 'Address',
    'hotels.shippingAddress': 'Shipping Address',
    'hotels.phone': 'Phone',
    'hotels.email': 'Email',
    'hotels.city': 'City',
    'hotels.postalCode': 'Postal Code',
    'hotels.website': 'Website',
    'hotels.contactPerson': 'Contact Person',
    'hotels.contactPhone': 'Contact Phone',
    'hotels.logo': 'Logo',
    'hotels.uploadLogo': 'Upload Logo',
    'hotels.removeLogo': 'Remove Logo',
    'hotels.noHotels': 'No hotels found',
    'hotels.editHotel': 'Edit Hotel',
    'hotels.addHotel': 'Add Hotel',
    'hotels.saveSuccess': 'Hotel saved successfully',
    'hotels.saveFailed': 'Failed to save hotel',
    'hotels.viewOnly': 'View Only',

    // Common
    'common.search': 'Search',
    'common.save': 'Save',
    'common.update': 'Update',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.view': 'View',
    'common.saving': 'Saving...',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.noData': 'No data available',
    'common.code': 'Code',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.total': 'Total',
    'common.all': 'All',

    // Status
    'status.draft': 'Draft',
    'status.submitted': 'Submitted',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.cancelled': 'Cancelled',
    'status.converted': 'Converted',
    'status.sent': 'Sent',
    'status.partial': 'Partial',
    'status.received': 'Received',
    'status.inProgress': 'In Progress',
    'status.completed': 'Completed',
    'status.confirmed': 'Confirmed',
    'status.pending': 'Pending Approval',

    // Dashboard
    'dashboard.overview': 'Overview for',
    'dashboard.totalActiveItems': 'Total Active Items',
    'dashboard.activeVendors': 'Active Vendors',
    'dashboard.outOfStock': 'Out of Stock',
    'dashboard.pendingPR': 'Pending PR',
    'dashboard.recentMovements': 'Recent Stock Movements',
    'dashboard.item': 'Item',
    'dashboard.type': 'Type',
    'dashboard.qty': 'Qty',
    'dashboard.balance': 'Balance',

    // Items
    'items.title': 'Master Items',
    'items.registered': 'items registered',
    'items.addItem': 'Add Item',
    'items.editItem': 'Edit Item',
    'items.addNew': 'Add New Item',
    'items.searchPlaceholder': 'Search items...',
    'items.code': 'Item Code',
    'items.name': 'Item Name',
    'items.namePlaceholder': 'e.g. Duvet Cover 180x200 Wonderfull',
    'items.nameHint': 'Format: [Item Name] [Size] [Brand]',
    'items.category': 'Category',
    'items.unit': 'Unit',
    'items.minStock': 'Min Stock',
    'items.maxStock': 'Max Stock',
    'items.reorderPoint': 'Reorder Point',
    'items.selectCategory': 'Select Category',
    'items.selectUnit': 'Select Unit',
    'items.purchaseUnit': 'Purchase Unit',
    'items.usageUnit': 'Usage Unit',
    'items.conversionRate': 'Conversion',
    'items.conversionHint': '1 Purchase Unit = ? Usage Unit',
    'items.selectPurchaseUnit': 'Select Purchase Unit',
    'items.selectUsageUnit': 'Select Usage Unit',
    'items.optionalDesc': 'Optional description',
    'items.brand': 'Brand',
    'items.size': 'Size',
    'items.brandPlaceholder': 'e.g. Unilever, 3M',
    'items.sizePlaceholder': 'e.g. 500ml, Large, 30x40cm',
    'items.defaultWarehouse': 'Default Warehouse',
    'items.selectWarehouse': 'Select Default Warehouse',
    'items.successAdd': 'Item added successfully',
    'items.successUpdate': 'Item updated successfully',
    'items.codeAutoGenerated': 'Auto-generated from category',

    // Vendors
    'vendors.title': 'Master Vendors',
    'vendors.registered': 'vendors registered',
    'vendors.addVendor': 'Add Vendor',
    'vendors.editVendor': 'Edit Vendor',
    'vendors.addNew': 'Add New Vendor',
    'vendors.contactPerson': 'Contact Person',
    'vendors.phone': 'Phone',
    'vendors.email': 'Email',
    'vendors.city': 'City',
    'vendors.address': 'Address',
    'vendors.paymentTerms': 'Payment Terms (days)',
    'vendors.terms': 'Terms',
    'vendors.days': 'days',
    'vendors.successAdd': 'Vendor added successfully',
    'vendors.successUpdate': 'Vendor updated successfully',

    // Departments
    'departments.title': 'Departments',
    'departments.at': 'Departments at',

    // Warehouses
    'wh.title': 'Warehouses',
    'wh.subtitle': 'Warehouses at',
    'wh.addNew': 'Add Warehouse',
    'wh.editTitle': 'Edit Warehouse',
    'wh.code': 'Code',
    'wh.name': 'Name',
    'wh.description': 'Description',
    'wh.type': 'Type',
    'wh.type.general': 'General',
    'wh.type.store': 'Store',
    'wh.type.room': 'Room',
    'wh.status': 'Status',
    'wh.confirmDelete': 'Are you sure you want to delete this warehouse?',
    'wh.successSave': 'Warehouse saved successfully',
    'wh.successDelete': 'Warehouse deleted successfully',
    'wh.errorSave': 'Error saving warehouse',

    // Bed Formations
    'menu.bedFormations': 'Bed Formations',
    'bedFormation.title': 'Bed Formation Management',
    'bedFormation.addNew': 'Add Bed Formation',
    'bedFormation.editTitle': 'Edit Bed Formation',
    'bedFormation.code': 'Code',
    'bedFormation.name': 'Name',
    'bedFormation.confirmDelete': 'Delete this bed formation?',
    'bedFormation.successSave': 'Bed formation saved successfully',
    'bedFormation.successDelete': 'Bed formation deleted',
    'bedFormation.errorSave': 'Error saving bed formation',
    'bedFormation.roomCount': 'Rooms',
    'room.bedFormation': 'Bed Formation',

    // Room Types
    'menu.roomTypes': 'Room Types',
    'roomType.title': 'Room Type Management',
    'roomType.subtitle': 'Manage room types per hotel',
    'roomType.addNew': 'Add Room Type',
    'roomType.editTitle': 'Edit Room Type',
    'roomType.code': 'Code',
    'roomType.name': 'Name',
    'roomType.confirmDelete': 'Delete this room type?',
    'roomType.successSave': 'Room type saved successfully',
    'roomType.successDelete': 'Room type deleted',
    'roomType.errorSave': 'Error saving room type',
    'roomType.roomCount': 'Rooms',

    // Rooms
    'menu.rooms': 'Rooms',
    'room.title': 'Room Management',
    'room.subtitle': 'Manage hotel rooms and room warehouses',
    'room.addNew': 'Add Room',
    'room.editTitle': 'Edit Room',
    'room.roomNumber': 'Room Number',
    'room.floor': 'Floor',
    'room.roomType': 'Room Type',
    'room.type.standard': 'Standard',
    'room.type.superior': 'Superior',
    'room.type.deluxe': 'Deluxe',
    'room.type.suite': 'Suite',
    'room.type.connecting': 'Connecting',
    'room.warehouse': 'Warehouse',
    'room.isWarehouse': 'Use as Warehouse',
    'room.warehouseActive': 'Room Warehouse Active',
    'room.warehouseInactive': 'Not a Warehouse',
    'room.enableWarehouse': 'Enable as Warehouse',
    'room.disableWarehouse': 'Disable Warehouse',
    'room.confirmDelete': 'Delete this room?',
    'room.successSave': 'Room saved successfully',
    'room.successDelete': 'Room deleted successfully',
    'room.errorSave': 'Error saving room',
    'room.warehouseEnabled': 'Room warehouse enabled',
    'room.warehouseDisabled': 'Room warehouse disabled',
    'room.manageItems': 'Manage Items',
    'roomItems.title': 'Room Items Setup',
    'roomItems.subtitle': 'Define replace & refill items for room',
    'roomItems.replace': 'Replace',
    'roomItems.refill': 'Refill',
    'roomItems.addItem': 'Add Item',
    'roomItems.item': 'Item',
    'roomItems.type': 'Type',
    'roomItems.defaultQty': 'Default Qty',
    'roomItems.noItems': 'No items configured for this room',
    'roomItems.successAdd': 'Room item added',
    'roomItems.successDelete': 'Room item removed',
    'roomItems.errorAdd': 'Error adding room item',
    'roomItems.selectItem': 'Select Item',
    'roomItems.selectType': 'Select Type',
    'roomItems.duplicate': 'This item+type combination already exists',
    'roomChecklist.title': 'Activity Checklist',
    'roomChecklist.subtitle': 'Define activity checklist for room',
    'roomChecklist.addActivity': 'Add Activity',
    'roomChecklist.name': 'Activity Name',
    'roomChecklist.description': 'Description',
    'roomChecklist.noActivities': 'No activities defined for this room',
    'roomChecklist.successAdd': 'Activity added',
    'roomChecklist.successDelete': 'Activity removed',
    'roomChecklist.successUpdate': 'Activity updated',
    'roomChecklist.errorSave': 'Error saving activity',
    'roomChecklist.copyFrom': 'Copy From',
    'roomChecklist.copyFromRoom': 'Copy checklist from another room',
    'roomChecklist.copySuccess': 'Checklist copied successfully',
    'roomChecklist.confirmDelete': 'Remove this activity?',

    // Categories
    'cat.title': 'Item Categories',
    'cat.subtitle': 'Manage item categories',
    'cat.addNew': 'Add Category',
    'cat.editTitle': 'Edit Category',
    'cat.code': 'Code',
    'cat.name': 'Name',
    'cat.description': 'Description',
    'cat.parent': 'Parent Category',
    'cat.noParent': '— None (Top Level) —',
    'cat.status': 'Status',
    'cat.itemCount': 'Items',
    'cat.confirmDelete': 'Are you sure you want to delete this category?',
    'cat.errorSave': 'Error saving category',

    // Stock
    'stock.title': 'Stock Balance',
    'stock.subtitle': 'Stock balance at',
    'stock.searchPlaceholder': 'Search item or department...',
    'stock.dept': 'Dept',
    'stock.avgCost': 'Avg Cost',
    'stock.totalValue': 'Total Value',
    'stock.lastUpdate': 'Last Update',
    'stock.allCategories': 'All Categories',
    'stock.allWarehouses': 'All Warehouses',
    'stock.warehouse': 'Warehouse',
    'stock.totalItems': 'Total Items',
    'stock.lowStock': 'Low Stock Items',
    'common.clearFilters': 'Clear Filters',

    // Bin Card
    'bincard.title': 'Bin Card',
    'bincard.subtitle': 'Stock movement history',
    'bincard.ref': 'Reference',
    'bincard.cost': 'Cost',
    'bincard.notes': 'Notes',
    'bincard.allItems': 'All Items',
    'bincard.allTypes': 'All Types',
    'bincard.totalMovements': 'Total Movements',
    'bincard.totalIn': 'Total In',
    'bincard.totalOut': 'Total Out',
    'bincard.empty': 'No stock movements found',

    // PR
    'pr.title': 'Purchase Request',
    'pr.subtitle': 'Purchase request list',
    'pr.create': 'Create PR',
    'pr.number': 'PR No.',
    'pr.requester': 'Requester',
    'pr.priority': 'Priority',
    'pr.estTotal': 'Est. Total',
    'pr.empty': 'No Purchase Requests yet',
    'pr.featureComingSoon': 'Create PR feature coming soon',
    'pr.neededDate': 'Needed Date',
    'pr.addItem': 'Add Item',
    'pr.selectItem': 'Select Item',
    'pr.qty': 'Qty',
    'pr.estPrice': 'Est. Price',
    'pr.total': 'Total',
    'pr.successSave': 'Purchase Request saved',
    'pr.successDelete': 'Purchase Request deleted',
    'pr.confirmDelete': 'Delete this PR?',
    'pr.statusDraft': 'Draft',
    'pr.statusPending': 'Pending',
    'pr.statusApproved': 'Approved',
    'pr.statusRejected': 'Rejected',
    'pr.convertToPO': 'Convert to PO',
    'pr.convertSuccess': 'PR converted to PO successfully',
    'pr.submit': 'Submit',
    'pr.approve': 'Approve',
    'pr.reject': 'Reject',
    'pr.items': 'Items',

    // PO
    'po.title': 'Purchase Order',
    'po.subtitle': 'Purchase order list',
    'po.create': 'Create PO',
    'po.number': 'PO No.',
    'po.vendor': 'Vendor',
    'po.empty': 'No Purchase Orders yet',
    'po.featureComingSoon': 'Create PO feature coming soon',
    'po.addItem': 'Add Item',
    'po.unitPrice': 'Unit Price',
    'po.qty': 'Qty',
    'po.discount': 'Disc %',
    'po.tax': 'Tax %',
    'po.lineTotal': 'Line Total',
    'po.successSave': 'Purchase Order saved',
    'po.successDelete': 'Purchase Order deleted',
    'po.confirmDelete': 'Delete this PO?',
    'po.expectedDelivery': 'Expected Delivery',
    'po.selectVendor': 'Select Vendor',
    'po.fromPR': 'From PR',
    'po.statusDraft': 'Draft',
    'po.statusSent': 'Sent',
    'po.statusPartial': 'Partial',
    'po.statusReceived': 'Received',
    'po.statusCancelled': 'Cancelled',
    'po.orderDate': 'Order Date',
    'po.paymentTerms': 'Payment Terms',
    'po.notes': 'Notes',
    'po.subtotal': 'Subtotal',
    'po.taxAmount': 'Tax Amount',
    'po.discountAmount': 'Discount Amount',
    'po.totalAmount': 'Total Amount',
    'po.submit': 'Submit',
    'po.approve': 'Approve',
    'po.reject': 'Reject',
    'po.send': 'Send to Vendor',
    'po.receive': 'Receive',
    'po.items': 'Items',

    // Stock Opname
    'opname.title': 'Stock Opname',
    'opname.subtitle': 'Stock opname assignments & physical count',
    'opname.create': 'Create Assignment',
    'opname.number': 'Opname No.',
    'opname.type': 'Type',
    'opname.variance': 'Variance',
    'opname.empty': 'No Stock Opname assignments yet',
    'opname.featureComingSoon': 'Create Stock Opname feature coming soon',
    'opname.date': 'Opname Date',
    'opname.department': 'Department',
    'opname.selectDept': 'Select Department',
    'opname.typeRoutine': 'Routine',
    'opname.typeAnnual': 'Annual',
    'opname.typeSpot': 'Spot Check',
    'opname.systemQty': 'System Qty',
    'opname.physicalQty': 'Physical Qty',
    'opname.varianceQty': 'Variance',
    'opname.unitCost': 'Unit Cost',
    'opname.varianceValue': 'Variance Value',
    'opname.loadItems': 'Load Items',
    'opname.successSave': 'Stock Opname assignment created',
    'opname.successDelete': 'Stock Opname deleted',
    'opname.confirmDelete': 'Delete this Stock Opname assignment?',
    'opname.statusDraft': 'Draft',
    'opname.statusPending': 'Pending',
    'opname.statusCounting': 'Counting',
    'opname.statusSubmitted': 'Submitted',
    'opname.statusVerified': 'Verified',
    'opname.statusApproved': 'Approved',
    'opname.statusRejected': 'Rejected',
    'opname.totalVariance': 'Total Variance',
    'opname.notes': 'Notes',
    'opname.submit': 'Submit Counting',
    'opname.verify': 'Verify',
    'opname.approve': 'Approve',
    'opname.category': 'Item Category',
    'opname.selectCategory': 'Select Category',
    'opname.assignedTo': 'Assigned To',
    'opname.selectUser': 'Select User',
    'opname.assignedBy': 'Assigned By',
    'opname.startCounting': 'Start Counting',
    'opname.openDetail': 'Open Detail',
    'opname.submitCounting': 'Submit Counting',
    'opname.confirmStart': 'Start counting this assignment? Items will be locked from transactions.',
    'opname.confirmSubmit': 'Submit counting results for approval?',
    'opname.selectItems': 'Select Items',
    'opname.selectAll': 'Select All',
    'opname.selectedCount': 'items selected',
    'opname.noPermission': 'Only GM / Finance Director can create opname assignments',
    'opname.countingStarted': 'Counting started',
    'opname.countingSubmitted': 'Counting submitted for approval',

    // Write-Off
    'writeoff.title': 'Write-Off',
    'writeoff.subtitle': 'Stock write-off list',
    'writeoff.create': 'Create Write-Off',
    'writeoff.number': 'WO No.',
    'writeoff.reason': 'Reason',
    'writeoff.totalValue': 'Total Value',
    'writeoff.empty': 'No Write-Offs yet',
    'writeoff.featureComingSoon': 'Create Write-off feature coming soon',
    'writeoff.date': 'Write-Off Date',
    'writeoff.department': 'Department',
    'writeoff.addItem': 'Add Item',
    'writeoff.qty': 'Qty',
    'writeoff.unitCost': 'Unit Cost',
    'writeoff.lineTotal': 'Total',
    'writeoff.successSave': 'Write-Off saved',
    'writeoff.successDelete': 'Write-Off deleted',
    'writeoff.confirmDelete': 'Delete this Write-Off?',
    'writeoff.statusDraft': 'Draft',
    'writeoff.statusPending': 'Pending',
    'writeoff.statusApproved': 'Approved',
    'writeoff.submit': 'Submit',
    'writeoff.approve': 'Approve',
    'writeoff.notes': 'Notes',
    'writeoff.reasonExpired': 'Expired',
    'writeoff.reasonDamaged': 'Damaged',
    'writeoff.reasonLost': 'Lost',
    'writeoff.reasonObsolete': 'Obsolete',
    'writeoff.reasonOther': 'Other',

    // Backdate Control
    'backdate.maxBackdateDays': 'Max Backdate Days',
    'backdate.gracePeriodDays': 'Grace Period Days',
    'backdate.periodLocked': 'Period is locked',
    'backdate.dateTooOld': 'Date exceeds maximum backdate limit',
    'backdate.periodLocks': 'Period Locks',
    'backdate.reopenPeriod': 'Reopen Period',
    'backdate.lockPeriod': 'Lock Period',
    'backdate.autoLocked': 'Auto-locked',
    'backdate.manualLocked': 'Manually locked',
    'backdate.reopenedBy': 'Reopened by',

    // Purchase Invoice
    'pi.title': 'Purchase Invoice',
    'pi.subtitle': 'Purchase invoice list',
    'pi.create': 'Create Invoice',
    'pi.number': 'PI No.',
    'pi.invoiceNumber': 'Vendor Invoice No.',
    'pi.invoiceDate': 'Invoice Date',
    'pi.dueDate': 'Due Date',
    'pi.vendor': 'Vendor',
    'pi.selectVendor': 'Select Vendor',
    'pi.empty': 'No Purchase Invoices yet',
    'pi.addItem': 'Add Item',
    'pi.unitPrice': 'Unit Price',
    'pi.qty': 'Qty',
    'pi.discount': 'Disc %',
    'pi.tax': 'Tax %',
    'pi.lineTotal': 'Line Total',
    'pi.subtotal': 'Subtotal',
    'pi.taxAmount': 'Tax Amount',
    'pi.discountAmount': 'Discount Amount',
    'pi.totalAmount': 'Total Amount',
    'pi.successSave': 'Purchase Invoice saved',
    'pi.successDelete': 'Purchase Invoice deleted',
    'pi.confirmDelete': 'Delete this Purchase Invoice?',
    'pi.statusDraft': 'Draft',
    'pi.statusPending': 'Pending',
    'pi.statusApproved': 'Approved',
    'pi.statusPaid': 'Paid',
    'pi.statusCancelled': 'Cancelled',
    'pi.paymentStatus': 'Payment',
    'pi.paymentUnpaid': 'Unpaid',
    'pi.paymentPartial': 'Partial',
    'pi.paymentPaid': 'Paid',
    'pi.submit': 'Submit',
    'pi.approve': 'Approve',
    'pi.reject': 'Reject',
    'pi.markPaid': 'Mark Paid',
    'pi.notes': 'Notes',
    'pi.fromPO': 'From PO',
    'pi.selectPO': 'Select PO to import',
    'pi.importFromPO': 'Import from PO',
    'pi.convertSuccess': 'PO converted to Invoice',
    'pi.items': 'Items',

    // Purchase Received (Goods Receipt)
    'menu.gr': 'Purchase Received',
    'gr.title': 'Purchase Received',
    'gr.subtitle': 'Receive goods from Purchase Invoices',
    'gr.create': 'New Receipt',
    'gr.number': 'GR Number',
    'gr.selectPI': 'Select Purchase Invoice',
    'gr.receivedDate': 'Received Date',
    'gr.fromPI': 'From PI',
    'gr.piQty': 'PI Qty',
    'gr.receivedQty': 'Receive Qty',
    'gr.prevReceived': 'Already Received',
    'gr.remaining': 'Remaining',
    'gr.warehouse': 'Target Warehouse',
    'gr.selectWarehouse': 'Select Warehouse',
    'gr.confirm': 'Confirm Receipt',
    'gr.successSave': 'Goods receipt saved',
    'gr.successConfirm': 'Goods receipt confirmed & stock updated',
    'gr.successDelete': 'Goods receipt deleted',
    'gr.confirmDelete': 'Delete this goods receipt?',
    'gr.confirmReceipt': 'Confirm this receipt? Stock will be updated.',
    'gr.empty': 'No goods receipts yet',
    'gr.notes': 'Notes',
    'gr.errorSave': 'Error saving goods receipt',
    'gr.errorOverQty': 'Receive qty exceeds remaining PI qty',
    'gr.errorNoWarehouse': 'Please select target warehouse for',
    'gr.status': 'Status',
    'gr.items': 'Items',

    // Room Make Up
    'makeup.title': 'Room Make Up',
    'makeup.subtitle': 'Housekeeping room makeup for',
    'makeup.newMakeup': 'New Make Up',
    'makeup.number': 'Makeup #',
    'makeup.room': 'Room',
    'makeup.selectRoom': 'Select Room',
    'makeup.searchPlaceholder': 'Search makeup...',
    'makeup.replaceItems': 'Replace Items',
    'makeup.refillItems': 'Refill Items',
    'makeup.defaultQty': 'Default',
    'makeup.actualQty': 'Actual',
    'makeup.dirtyQty': 'Dirty',
    'makeup.warehouse': 'Warehouse',
    'makeup.itemCount': 'Items',
    'makeup.notes': 'Notes',
    'makeup.notesPlaceholder': 'Optional notes...',
    'makeup.saveDraft': 'Save as Draft',
    'makeup.confirm': 'Confirm',
    'makeup.confirmMsg': 'Confirm this room makeup? Stock will be updated.',
    'makeup.successSave': 'Room makeup saved',
    'makeup.successConfirm': 'Room makeup confirmed & stock updated',
    'makeup.errorSave': 'Error saving room makeup',
    'makeup.lostBreakage': 'Lost & Breakage',
    'makeup.lbItems': 'Lost/Damaged Items',
    'makeup.addLBItem': 'Add Lost/Damaged Item',
    'makeup.lbSelectItem': 'Select Item',
    'makeup.lbQty': 'Qty',
    'makeup.lbReason': 'Reason',
    'makeup.lbReasonLost': 'Lost',
    'makeup.lbReasonDamaged': 'Damaged',
    'makeup.lbSourceWarehouse': 'Replacement From',
    'makeup.lbNoItems': 'No lost/damaged items',
    'makeup.activityChecklist': 'Activity Checklist',
    'makeup.activityChecklistDesc': 'Completion status',
    'makeup.noActivityTemplates': 'No activity templates configured',
    'makeup.inuseVerification': 'In-Use Verification',
    'makeup.inuseVerificationDesc': 'Stock balance check',
    'makeup.expectedQty': 'Expected',
    'makeup.difference': 'Diff',
    'makeup.noInuseItems': 'No in-use items to verify',

    // Laundry
    'laundry.title': 'Laundry Management',
    'laundry.subtitle': 'Manage linen laundry cycle for',
    'laundry.sendTab': 'Kirim ke Laundry',
    'laundry.receiveTab': 'Terima dari Laundry',
    'laundry.itemsInDirty': 'Items di Dirty',
    'laundry.itemsInLaundry': 'Items di Laundry',
    'laundry.selectedCount': 'Dipilih untuk Transfer',
    'laundry.searchPlaceholder': 'Cari item berdasarkan nama, kode, atau brand...',
    'laundry.allCategories': 'Semua Kategori',
    'laundry.noDirtyWarehouse': 'Belum ada dirty warehouse untuk hotel ini.',
    'laundry.noLaundryWarehouse': 'Belum ada laundry warehouse untuk hotel ini.',
    'laundry.noDirtyItems': 'Tidak ada item di dirty warehouse.',
    'laundry.noLaundryItems': 'Tidak ada item di laundry warehouse.',
    'laundry.itemCode': 'Kode Item',
    'laundry.itemName': 'Nama Item',
    'laundry.category': 'Kategori',
    'laundry.availableQty': 'Qty Tersedia',
    'laundry.transferQty': 'Qty Transfer',
    'laundry.notes': 'Catatan',
    'laundry.sendButton': 'Kirim ke Laundry',
    'laundry.receiveButton': 'Terima dari Laundry',
    'laundry.successSend': 'Berhasil kirim ke laundry',
    'laundry.successReceive': 'Berhasil terima dari laundry',
    'laundry.errorSend': 'Gagal kirim ke laundry',
    'laundry.errorReceive': 'Gagal terima dari laundry',
    'laundry.noItemsSelected': 'Pilih minimal 1 item untuk ditransfer',
    'laundry.history': 'Riwayat Laundry',
    'laundry.noHistory': 'Belum ada riwayat laundry.',
    'laundry.typeSend': 'Kirim',
    'laundry.typeReceive': 'Terima',

    // Transfer
    'transfer.title': 'Stock Transfer',
    'transfer.subtitle': 'Transfer items between warehouses for',
    'transfer.newTransfer': 'New Transfer',
    'transfer.number': 'Transfer #',
    'transfer.from': 'From',
    'transfer.to': 'To',
    'transfer.selectWarehouse': 'Select Warehouse',
    'transfer.selectItem': 'Select Item',
    'transfer.searchPlaceholder': 'Search transfer...',
    'transfer.items': 'Transfer Items',
    'transfer.addItem': 'Add Item',
    'transfer.notes': 'Notes',
    'transfer.saveDraft': 'Save as Draft',
    'transfer.confirm': 'Confirm',
    'transfer.confirmMsg': 'Confirm this transfer? Stock movements will be recorded.',
    'transfer.successSave': 'Transfer saved',
    'transfer.successConfirm': 'Transfer confirmed & stock updated',
    'transfer.errorSave': 'Error saving transfer',
    'transfer.selectWarehouses': 'Please select source and destination warehouses',
    'transfer.sameWarehouse': 'Source and destination must be different',
    'transfer.addItems': 'Please add at least one item',

    // Direct Purchase
    'dp.title': 'Direct Purchase',
    'dp.subtitle': 'Direct purchase without vendor for',
    'dp.create': 'New Direct Purchase',
    'dp.number': 'DP #',
    'dp.date': 'Purchase Date',
    'dp.location': 'Purchase Location',
    'dp.locationPlaceholder': 'e.g. Pasar Baru, Tokopedia, Alfamart',
    'dp.searchPlaceholder': 'Search direct purchase...',
    'dp.items': 'Purchase Items',
    'dp.addItem': 'Add Item',
    'dp.selectItem': 'Select Item',
    'dp.qty': 'Qty',
    'dp.unitPrice': 'Unit Price',
    'dp.totalPrice': 'Total',
    'dp.warehouse': 'Warehouse',
    'dp.selectWarehouse': 'Select Warehouse',
    'dp.notes': 'Notes',
    'dp.saveDraft': 'Save as Draft',
    'dp.confirm': 'Received',
    'dp.confirmMsg': 'Mark as received? Stock will be updated.',
    'dp.successSave': 'Direct purchase saved',
    'dp.successConfirm': 'Direct purchase received & stock updated',
    'dp.errorSave': 'Error saving direct purchase',
    'dp.empty': 'No direct purchases yet',
    'dp.confirmDelete': 'Delete this direct purchase?',
    'dp.successDelete': 'Direct purchase deleted',
    'dp.grandTotal': 'Grand Total',
    'dp.addItems': 'Please add at least one item',
    'dp.locationRequired': 'Purchase location is required',

    // Single Item Usage
    'menu.singleUsage': 'Single Item Usage',
    'siu.title': 'Single Item Usage',
    'siu.subtitle': 'Record single item usage for',
    'siu.create': 'Record Usage',
    'siu.number': 'Usage #',
    'siu.date': 'Usage Date',
    'siu.item': 'Item',
    'siu.selectItem': 'Select Item',
    'siu.warehouse': 'From Warehouse',
    'siu.selectWarehouse': 'Select Warehouse',
    'siu.department': 'Department',
    'siu.selectDepartment': 'Select Department',
    'siu.qty': 'Quantity',
    'siu.qtyMax1': 'Max quantity is 1',
    'siu.notes': 'Notes',
    'siu.confirm': 'Confirm Usage',
    'siu.confirmMsg': 'Confirm this usage? Stock will be reduced immediately.',
    'siu.successConfirm': 'Usage recorded & stock updated',
    'siu.errorSave': 'Error recording usage',
    'siu.empty': 'No usage records yet',
    'siu.searchPlaceholder': 'Search usage records...',
    'siu.itemRequired': 'Please select an item',
    'siu.warehouseRequired': 'Please select a warehouse',
    'siu.departmentRequired': 'Please select a department',
    'siu.noStock': 'Insufficient stock in selected warehouse',
    'siu.usedBy': 'Used By',

    // In-Use Warehouse
    'menu.inUseWarehouse': 'In-Use Warehouse',
    'iu.title': 'In-Use Warehouse',
    'iu.subtitle': 'Track reusable items currently in use for',
    'iu.filterCategory': 'Filter by Category',
    'iu.allCategories': 'All Categories',
    'iu.item': 'Item',
    'iu.category': 'Category',
    'iu.qty': 'Qty',
    'iu.status': 'Status',
    'iu.inUse': 'In Use',
    'iu.markDepleted': 'Mark Depleted',
    'iu.depletedConfirm': 'Mark this item as depleted? Stock will be removed from In-Use warehouse.',
    'iu.depletedSuccess': 'Item marked as depleted',
    'iu.depletedError': 'Error marking item as depleted',
    'iu.empty': 'No items currently in use',
    'iu.searchPlaceholder': 'Search in-use items...',
    'iu.lastUpdated': 'Last Updated',
    'iu.warehouse': 'In-Use Warehouse',

    // Approval
    'approval.approvedBy': 'Approved by',
    'approval.approvedAt': 'Approved at',
    'approval.rejectedBy': 'Rejected by',
    'approval.rejectedAt': 'Rejected at',
    'approval.info': 'Approval Info',
    'approval.confirmApprove': 'Approve this document?',
    'approval.confirmReject': 'Reject this document?',
    'approval.notApproved': 'Not yet approved',
    'approval.pageTitle': 'Approval Center',
    'approval.pageSubtitle': 'Review and approve pending documents',
    'approval.pending': 'Pending',
    'approval.history': 'History',
    'approval.noPending': 'No pending approvals',
    'approval.approve': 'Approve',
    'approval.reject': 'Reject',
    'approval.rejectReason': 'Rejection reason',
    'approval.gmApproved': 'GM Approved',
    'approval.findirApproved': 'FinDir Approved',
    'approval.waitingGM': 'Waiting GM',
    'approval.waitingFinDir': 'Waiting Finance Director',
    'approval.waitingBoth': 'Waiting GM & Finance Director',
    'approval.submittedBy': 'Submitted by',
    'approval.submittedAt': 'Submitted at',
    'menu.approval': 'Approval',

    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Inventory summary and analysis',
    'reports.totalStockValue': 'Total Stock Value',
    'reports.totalSKU': 'Total SKU',
    'reports.hotel': 'Hotel',
    'reports.valuationReport': 'Stock Valuation Report',
    'reports.selectReport': 'Select Report',
    'reports.stockValuation': 'Stock Valuation',
    'reports.stockMovement': 'Stock Movement',
    'reports.purchaseSummary': 'Purchase Summary',
    'reports.lowStock': 'Low Stock Alert',
    'reports.opnameSummary': 'Opname Summary',
    'reports.filterCategory': 'Category',
    'reports.filterDept': 'Department',
    'reports.filterDateFrom': 'From Date',
    'reports.filterDateTo': 'To Date',
    'reports.allCategories': 'All Categories',
    'reports.allDepts': 'All Departments',
    'reports.generate': 'Generate',
    'reports.exportPDF': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.noData': 'No data for this report. Adjust filters and try again.',
    'reports.movementType': 'Type',
    'reports.movementQty': 'Qty',
    'reports.reference': 'Reference',
    'reports.poNumber': 'PO No.',
    'reports.piNumber': 'PI No.',
    'reports.vendorName': 'Vendor',
    'reports.totalPO': 'Total POs',
    'reports.totalPI': 'Total PIs',
    'reports.totalPOValue': 'Total PO Value',
    'reports.totalPIValue': 'Total PI Value',
    'reports.minStock': 'Min Stock',
    'reports.currentStock': 'Current Stock',
    'reports.shortage': 'Shortage',
    'reports.opnameNumber': 'Opname No.',
    'reports.varianceValue': 'Variance Value',

    // Opening Balance
    // Opening Balance
    'ob.title': 'Opening Balance',
    'ob.subtitle': 'Initial stock opname per category',
    'ob.menu': 'Opening Balance',
    'ob.selectCategory': 'Select a category to start counting',
    'ob.itemCode': 'Item Code',
    'ob.itemName': 'Item Name',
    'ob.unit': 'Unit',
    'ob.category': 'Category',
    'ob.qtyOnHand': 'Qty on Hand',
    'ob.unitCost': 'Unit Cost (Rp)',
    'ob.totalValue': 'Total Value',
    'ob.totalQty': 'Total Qty',
    'ob.save': 'Save',
    'ob.saving': 'Saving...',
    'ob.successSave': 'Opening balance saved successfully',
    'ob.errorSave': 'Error saving',
    'ob.noItems': 'No items in this category.',
    'ob.totalItems': 'Total Items',
    'ob.itemsCounted': 'Items Counted',
    'ob.totalStockValue': 'Total Stock Value',
    'ob.locked': 'Locked',
    'ob.lockWarning': 'Once locked, this category cannot be modified. Make sure all data is correct.',
    'ob.lockConfirm': 'Are you sure you want to lock this category? This action cannot be undone.',
    'ob.lockBtn': 'Lock Category',
    'ob.unlocked': 'Draft',
    'ob.lockedStatus': 'Locked',
    'ob.searchPlaceholder': 'Search items...',
    'ob.backToCategories': 'Back to Categories',
    'ob.progress': 'Progress',
    'ob.items': 'items',
    'ob.allCategories': 'All Categories',
    'ob.categoriesLocked': 'Categories Locked',
    'ob.draft': 'Draft',
    'ob.completed': 'Completed',
    'ob.startCounting': 'Start Counting',
    'ob.continue': 'Continue',
    'ob.view': 'View',
    'ob.inStock': 'In Stock',
    'ob.inUse': 'In Use',
    'ob.dirty': 'Dirty',
    'ob.inLaundry': 'In Laundry',
    'ob.damaged': 'Damaged',
    'ob.totalPcs': 'Total Pcs',
    // Fixed Asset statuses
    'ob.good': 'Good',
    'ob.fair': 'Fair',
    'ob.poor': 'Poor',
    // Machinery statuses
    'ob.operational': 'Operational',
    'ob.maintenance': 'Under Maintenance',
    'ob.broken': 'Broken/Out of Service',

    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Create and manage users',
    'users.users': 'Users',
    'users.fullName': 'Full Name',
    'users.username': 'Username',
    'users.role': 'Role',
    'users.hotel': 'Hotel',
    'users.email': 'Email',
    'users.phone': 'Phone',
    'users.department': 'Department',
    'users.createUser': 'Create User',
    'users.editUser': 'Edit User',
    'users.selectRole': 'Select Role',
    'users.selectHotel': 'Select Hotel',
    'users.selectDept': 'Select Department',
    'users.allHotels': 'All Hotels (Corporate)',
    'users.successSave': 'User saved successfully',
    'users.successDelete': 'User deleted successfully',
    'users.confirmDelete': 'Delete this user?',
    'users.password': 'Password',
    'users.passwordHint': 'Min 6 characters (leave blank to keep current)',

    // Role Management
    'roles.title': 'Role Management',
    'roles.subtitle': 'Define access permissions for each role',
    'roles.roles': 'Roles',
    'roles.createRole': 'Create Role',
    'roles.editRole': 'Edit Role',
    'roles.roleName': 'Role Name',
    'roles.description': 'Description',
    'roles.system': 'System',
    'roles.menuAccess': 'Menu Access',
    'roles.specialActions': 'Special Actions',
    'roles.successSave': 'Role saved successfully',
    'roles.successDelete': 'Role deleted successfully',
    'roles.confirmDelete': 'Delete this role?',
    'roles.cannotDeleteSystem': 'Cannot delete system role',
    'roles.permissions': 'Permissions',
    'roles.action.approve_pr': 'Approve PR',
    'roles.action.approve_po': 'Approve PO',
    'roles.action.approve_pi': 'Approve Invoice',
    'roles.action.approve_wo': 'Approve Write-Off',
    'roles.action.approve_opname': 'Approve Opname',
    'roles.action.revoke_approval': 'Revoke Approval',
    'roles.action.revert_to_draft': 'Revert to Draft',
    'roles.action.export_reports': 'Export Reports',
    'roles.action.manage_users': 'Manage Users',
    'roles.action.manage_roles': 'Manage Roles',
    'roles.action.unlock_opening_balance': 'Unlock Opening Balance',
    'roles.action.view_all_room_makeups': 'View All Room Make Ups',

    // System Settings
    'settings.title': 'System Settings',
    'settings.subtitle': 'Configure system-wide preferences',
    'settings.timezone': 'Timezone',
    'settings.timezoneDesc': 'Timezone used for all date/time displays',
    'settings.currency': 'Currency',
    'settings.currencyDesc': 'Default currency for financial data',
    'settings.dateFormat': 'Date Format',
    'settings.dateFormatDesc': 'Display format for dates throughout the system',
    'settings.language': 'Default Language',
    'settings.languageDesc': 'Default interface language for new users',
    'settings.lowStockThreshold': 'Low Stock Threshold',
    'settings.lowStockThresholdDesc': 'Default threshold for low stock alerts',
    'settings.autoGenerateCode': 'Auto Generate Codes',
    'settings.autoGenerateCodeDesc': 'Automatically generate item/document codes',
    'settings.fiscalYearStart': 'Fiscal Year Start Month',
    'settings.fiscalYearStartDesc': 'Starting month of the fiscal year',
    'settings.saved': 'Settings saved successfully',
    'settings.saveError': 'Failed to save settings',
    'settings.save': 'Save Settings',
    'settings.saving': 'Saving...',
    'settings.general': 'General',
    'settings.inventory': 'Inventory',
    'settings.regional': 'Regional',
    'settings.maintenance': 'Maintenance',
    'settings.maintenanceMode': 'Maintenance Mode',
    'settings.maintenanceModeDesc': 'When enabled, all users except superadmin and authorized roles will be logged out and blocked from accessing the system.',
    'settings.maintenanceOn': 'MAINTENANCE ON',
    'settings.maintenanceOff': 'Normal Operation',
    'settings.maintenanceWarning': 'Enabling maintenance mode will immediately kick all unauthorized users. Make sure to notify your team before activating.',
    'settings.maintenanceActive': 'Maintenance mode is currently ACTIVE. Only superadmin and roles with maintenance access can use the system.',
    'roles.allowMaintenanceAccess': 'Allow Maintenance Access',
    'roles.allowMaintenanceAccessDesc': 'Users with this role can still access the system during maintenance mode',
    'menu.systemSettings': 'System Settings',
    'menu.cronJobs': 'CRON Jobs',

    // Change Password
    'pwd.title': 'Change Password',
    'pwd.subtitle': 'Update your account password',
    'pwd.currentPassword': 'Current Password',
    'pwd.newPassword': 'New Password',
    'pwd.confirmPassword': 'Confirm New Password',
    'pwd.change': 'Change Password',
    'pwd.success': 'Password changed successfully',
    'pwd.errorMismatch': 'New passwords do not match',
    'pwd.errorShort': 'Password must be at least 6 characters',
    'pwd.errorCurrent': 'Current password is incorrect',
    'pwd.selectUser': 'Select User',
  },
  zh: {
    // App
    'app.title': '酒店库存',
    'app.subtitle': '管理系统',
    'app.loading': '正在加载库存系统...',
    'app.version': __APP_VERSION__,
    'app.accessDenied': '访问被拒绝',
    'app.noPermission': '您没有权限访问此页面。',
    'app.maintenance.title': '系统维护中',
    'app.maintenance.message': '系统目前正在维护中，请稍后再试。',
    'app.maintenance.contact': '如需紧急帮助，请联系系统管理员。',

    // Menu
    // Login & Auth
    'login.title': '酒店库存管理系统',
    'login.subtitle': 'Delonix 酒店集团',
    'login.username': '用户名',
    'login.password': '密码',
    'login.signIn': '登录',
    'login.signingIn': '登录中...',
    'login.error': '用户名或密码错误',
    'login.logout': '退出登录',
    'login.welcome': '欢迎',
    'login.forceChange': '首次登录请修改密码',
    'login.newPassword': '新密码',
    'login.confirmNewPassword': '确认新密码',
    'login.changeAndContinue': '修改密码并继续',
    'login.passwordChanged': '密码修改成功',
    'login.passwordMismatch': '两次密码不一致',
    'login.passwordShort': '密码至少6个字符',

    'menu.dashboard': '仪表板',
    'menu.items': '物品管理',
    'menu.categories': '物品类别',
    'menu.vendors': '供应商',
    'menu.departments': '部门',
    'menu.warehouses': '仓库',
    'menu.stock': '库存余额',
    'menu.movements': '库存卡',
    'menu.pr': '采购申请',
    'menu.po': '采购订单',
    'menu.opname': '盘点',
    'menu.writeoff': '报废',
    'menu.pi': '采购发票',
    'menu.reports': '报表',
    'menu.userMgmt': '用户管理',
    'menu.roleMgmt': '角色管理',
    'menu.changePassword': '修改密码',
    'menu.group.globalMaster': '全局主数据',
    'menu.group.hotelMaster': '酒店主数据',
    'menu.group.purchase': '采购管理',
    'menu.group.stockIn': '入库',
    'menu.group.stockOut': '出库',
    'menu.group.stock': '库存管理',
    'menu.group.settings': '设置',
    'menu.roomMakeupNew': '客房整理 (新)',
    'menu.transfer': '调拨',
    'menu.directPurchase': '直接采购',
    'menu.hotels': '酒店',

    // Hotels Page
    'hotels.title': '酒店资料',
    'hotels.companyName': '公司名称 (PT)',
    'hotels.npwp': 'NPWP',
    'hotels.hotelName': '酒店名称',
    'hotels.hotelCode': '酒店代码',
    'hotels.address': '地址',
    'hotels.shippingAddress': '送货地址',
    'hotels.phone': '电话',
    'hotels.email': '邮箱',
    'hotels.city': '城市',
    'hotels.postalCode': '邮编',
    'hotels.website': '网站',
    'hotels.contactPerson': '联系人',
    'hotels.contactPhone': '联系电话',
    'hotels.logo': '标志',
    'hotels.uploadLogo': '上传标志',
    'hotels.removeLogo': '删除标志',
    'hotels.noHotels': '未找到酒店',
    'hotels.editHotel': '编辑酒店',
    'hotels.addHotel': '添加酒店',
    'hotels.saveSuccess': '酒店保存成功',
    'hotels.saveFailed': '保存酒店失败',
    'hotels.viewOnly': '仅查看',

    // Common
    'common.search': '搜索',
    'common.save': '保存',
    'common.update': '更新',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.view': '查看',
    'common.saving': '保存中...',
    'common.create': '创建',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.actions': '操作',
    'common.status': '状态',
    'common.active': '启用',
    'common.inactive': '停用',
    'common.noData': '暂无数据',
    'common.code': '编码',
    'common.name': '名称',
    'common.description': '描述',
    'common.date': '日期',
    'common.total': '合计',
    'common.all': '全部',

    // Status
    'status.draft': '草稿',
    'status.submitted': '已提交',
    'status.approved': '已批准',
    'status.rejected': '已拒绝',
    'status.cancelled': '已取消',
    'status.converted': '已转换',
    'status.sent': '已发送',
    'status.partial': '部分',
    'status.received': '已接收',
    'status.inProgress': '进行中',
    'status.completed': '已完成',
    'status.pending': '待审批',

    // Dashboard
    'dashboard.overview': '概览 -',
    'dashboard.totalActiveItems': '活跃物品总数',
    'dashboard.activeVendors': '活跃供应商',
    'dashboard.outOfStock': '缺货',
    'dashboard.pendingPR': '待处理采购申请',
    'dashboard.recentMovements': '最近库存变动',
    'dashboard.item': '物品',
    'dashboard.type': '类型',
    'dashboard.qty': '数量',
    'dashboard.balance': '余额',

    // Items
    'items.title': '物品管理',
    'items.registered': '件物品已登记',
    'items.addItem': '添加物品',
    'items.editItem': '编辑物品',
    'items.addNew': '添加新物品',
    'items.searchPlaceholder': '搜索物品...',
    'items.code': '物品编码',
    'items.name': '物品名称',
    'items.namePlaceholder': '例如 羽绒被套 180x200 Wonderfull',
    'items.nameHint': '格式：[物品名称] [规格] [品牌]',
    'items.category': '类别',
    'items.unit': '单位',
    'items.minStock': '最低库存',
    'items.maxStock': '最高库存',
    'items.reorderPoint': '再订货点',
    'items.selectCategory': '选择类别',
    'items.selectUnit': '选择单位',
    'items.purchaseUnit': '采购单位',
    'items.usageUnit': '使用单位',
    'items.conversionRate': '换算率',
    'items.conversionHint': '1 采购单位 = ? 使用单位',
    'items.selectPurchaseUnit': '选择采购单位',
    'items.selectUsageUnit': '选择使用单位',
    'items.optionalDesc': '可选描述',
    'items.brand': '品牌',
    'items.size': '规格',
    'items.brandPlaceholder': '例如 联合利华、3M',
    'items.sizePlaceholder': '例如 500ml、大号、30x40cm',
    'items.defaultWarehouse': '默认仓库',
    'items.selectWarehouse': '选择默认仓库',
    'items.successAdd': '物品添加成功',
    'items.successUpdate': '物品更新成功',
    'items.codeAutoGenerated': '根据类别自动生成',

    // Vendors
    'vendors.title': '供应商管理',
    'vendors.registered': '家供应商已登记',
    'vendors.addVendor': '添加供应商',
    'vendors.editVendor': '编辑供应商',
    'vendors.addNew': '添加新供应商',
    'vendors.contactPerson': '联系人',
    'vendors.phone': '电话',
    'vendors.email': '邮箱',
    'vendors.city': '城市',
    'vendors.address': '地址',
    'vendors.paymentTerms': '付款条件（天）',
    'vendors.terms': '账期',
    'vendors.days': '天',
    'vendors.successAdd': '供应商添加成功',
    'vendors.successUpdate': '供应商更新成功',

    // Departments
    'departments.title': '部门',
    'departments.at': '部门 -',

    // Warehouses
    'wh.title': '仓库',
    'wh.subtitle': '仓库 -',
    'wh.addNew': '添加仓库',
    'wh.editTitle': '编辑仓库',
    'wh.code': '代码',
    'wh.name': '名称',
    'wh.description': '描述',
    'wh.type': '类型',
    'wh.type.general': '一般',
    'wh.type.store': '仓库',
    'wh.type.room': '客房',
    'wh.status': '状态',
    'wh.confirmDelete': '确定要删除此仓库吗？',
    'wh.successSave': '仓库保存成功',
    'wh.successDelete': '仓库删除成功',
    'wh.errorSave': '保存仓库出错',

    // Bed Formations
    'menu.bedFormations': '床型管理',
    'bedFormation.title': '床型管理',
    'bedFormation.addNew': '添加床型',
    'bedFormation.editTitle': '编辑床型',
    'bedFormation.code': '编码',
    'bedFormation.name': '名称',
    'bedFormation.confirmDelete': '确认删除此床型？',
    'bedFormation.successSave': '床型保存成功',
    'bedFormation.successDelete': '床型已删除',
    'bedFormation.errorSave': '保存床型出错',
    'bedFormation.roomCount': '客房数',
    'room.bedFormation': '床型',

    // Room Types
    'menu.roomTypes': '房型管理',
    'roomType.title': '房型管理',
    'roomType.subtitle': '管理各酒店房型',
    'roomType.addNew': '添加房型',
    'roomType.editTitle': '编辑房型',
    'roomType.code': '编码',
    'roomType.name': '名称',
    'roomType.confirmDelete': '确认删除此房型？',
    'roomType.successSave': '房型保存成功',
    'roomType.successDelete': '房型已删除',
    'roomType.errorSave': '保存房型出错',
    'roomType.roomCount': '客房数',

    // Rooms
    'menu.rooms': '客房',
    'room.title': '客房管理',
    'room.subtitle': '管理酒店客房和客房仓库',
    'room.addNew': '添加客房',
    'room.editTitle': '编辑客房',
    'room.roomNumber': '房间号',
    'room.floor': '楼层',
    'room.roomType': '房型',
    'room.type.standard': '标准间',
    'room.type.superior': '高级间',
    'room.type.deluxe': '豪华间',
    'room.type.suite': '套房',
    'room.type.connecting': '连通房',
    'room.warehouse': '仓库',
    'room.isWarehouse': '用作仓库',
    'room.warehouseActive': '客房仓库已启用',
    'room.warehouseInactive': '非仓库',
    'room.enableWarehouse': '启用为仓库',
    'room.disableWarehouse': '停用仓库',
    'room.confirmDelete': '确定删除此客房？',
    'room.successSave': '客房保存成功',
    'room.successDelete': '客房删除成功',
    'room.errorSave': '保存客房出错',
    'room.warehouseEnabled': '客房仓库已启用',
    'room.warehouseDisabled': '客房仓库已停用',
    'room.manageItems': '管理物品',
    'roomItems.title': '客房物品设置',
    'roomItems.subtitle': '定义客房的更换和补充物品',
    'roomItems.replace': '更换',
    'roomItems.refill': '补充',
    'roomItems.addItem': '添加物品',
    'roomItems.item': '物品',
    'roomItems.type': '类型',
    'roomItems.defaultQty': '默认数量',
    'roomItems.noItems': '该客房未配置物品',
    'roomItems.successAdd': '客房物品已添加',
    'roomItems.successDelete': '客房物品已移除',
    'roomItems.errorAdd': '添加客房物品出错',
    'roomItems.selectItem': '选择物品',
    'roomItems.selectType': '选择类型',
    'roomItems.duplicate': '该物品+类型组合已存在',
    'roomChecklist.title': '活动检查表',
    'roomChecklist.subtitle': '定义客房活动检查表',
    'roomChecklist.addActivity': '添加活动',
    'roomChecklist.name': '活动名称',
    'roomChecklist.description': '描述',
    'roomChecklist.noActivities': '该客房未定义活动',
    'roomChecklist.successAdd': '活动已添加',
    'roomChecklist.successDelete': '活动已移除',
    'roomChecklist.successUpdate': '活动已更新',
    'roomChecklist.errorSave': '保存活动出错',
    'roomChecklist.copyFrom': '复制自',
    'roomChecklist.copyFromRoom': '从其他客房复制检查表',
    'roomChecklist.copySuccess': '检查表复制成功',
    'roomChecklist.confirmDelete': '确定移除此活动？',

    // Categories
    'cat.title': '物品类别',
    'cat.subtitle': '管理物品类别',
    'cat.addNew': '添加类别',
    'cat.editTitle': '编辑类别',
    'cat.code': '代码',
    'cat.name': '名称',
    'cat.description': '描述',
    'cat.parent': '上级类别',
    'cat.noParent': '— 无（顶级）—',
    'cat.status': '状态',
    'cat.itemCount': '物品数',
    'cat.confirmDelete': '确定要删除此类别吗？',
    'cat.errorSave': '保存类别出错',

    // Stock
    'stock.title': '库存余额',
    'stock.subtitle': '库存余额 -',
    'stock.searchPlaceholder': '搜索物品或部门...',
    'stock.dept': '部门',
    'stock.avgCost': '平均成本',
    'stock.totalValue': '总价值',
    'stock.lastUpdate': '最后更新',
    'stock.allCategories': '所有类别',
    'stock.allWarehouses': '所有仓库',
    'stock.warehouse': '仓库',
    'stock.totalItems': '总项目',
    'stock.lowStock': '低库存项目',
    'common.clearFilters': '清除筛选',

    // Bin Card
    'bincard.title': '库存卡',
    'bincard.subtitle': '库存变动记录',
    'bincard.ref': '参考号',
    'bincard.cost': '成本',
    'bincard.notes': '备注',
    'bincard.allItems': '所有物品',
    'bincard.allTypes': '所有类型',
    'bincard.totalMovements': '总变动',
    'bincard.totalIn': '总入库',
    'bincard.totalOut': '总出库',
    'bincard.empty': '无库存变动记录',

    // PR
    'pr.title': '采购申请',
    'pr.subtitle': '采购申请列表',
    'pr.create': '创建采购申请',
    'pr.number': '申请编号',
    'pr.requester': '申请人',
    'pr.priority': '优先级',
    'pr.estTotal': '预估总额',
    'pr.empty': '暂无采购申请',
    'pr.featureComingSoon': '创建采购申请功能即将推出',
    'pr.neededDate': '需求日期',
    'pr.addItem': '添加物品',
    'pr.selectItem': '选择物品',
    'pr.qty': '数量',
    'pr.estPrice': '预估单价',
    'pr.total': '合计',
    'pr.successSave': '采购申请已保存',
    'pr.successDelete': '采购申请已删除',
    'pr.confirmDelete': '确定删除此采购申请？',
    'pr.statusDraft': '草稿',
    'pr.statusPending': '待审批',
    'pr.statusApproved': '已批准',
    'pr.statusRejected': '已拒绝',
    'pr.convertToPO': '转为采购订单',
    'pr.convertSuccess': '采购申请已转为采购订单',
    'pr.submit': '提交',
    'pr.approve': '批准',
    'pr.reject': '拒绝',
    'pr.items': '物品',

    // PO
    'po.title': '采购订单',
    'po.subtitle': '采购订单列表',
    'po.create': '创建采购订单',
    'po.number': '订单编号',
    'po.vendor': '供应商',
    'po.empty': '暂无采购订单',
    'po.featureComingSoon': '创建采购订单功能即将推出',
    'po.addItem': '添加物品',
    'po.unitPrice': '单价',
    'po.qty': '数量',
    'po.discount': '折扣 %',
    'po.tax': '税 %',
    'po.lineTotal': '行合计',
    'po.successSave': '采购订单已保存',
    'po.successDelete': '采购订单已删除',
    'po.confirmDelete': '确定删除此采购订单？',
    'po.expectedDelivery': '预计交货日期',
    'po.selectVendor': '选择供应商',
    'po.fromPR': '来自采购申请',
    'po.statusDraft': '草稿',
    'po.statusSent': '已发送',
    'po.statusPartial': '部分收货',
    'po.statusReceived': '已收货',
    'po.statusCancelled': '已取消',
    'po.orderDate': '订单日期',
    'po.paymentTerms': '付款条件',
    'po.notes': '备注',
    'po.subtotal': '小计',
    'po.taxAmount': '税额',
    'po.discountAmount': '折扣额',
    'po.totalAmount': '总金额',
    'po.submit': '提交',
    'po.approve': '批准',
    'po.reject': '拒绝',
    'po.send': '发送给供应商',
    'po.receive': '确认收货',
    'po.items': '物品',

    // Stock Opname
    'opname.title': '盘点',
    'opname.subtitle': '库存盘点任务与实物盘点',
    'opname.create': '创建盘点任务',
    'opname.number': '盘点编号',
    'opname.type': '类型',
    'opname.variance': '差异',
    'opname.empty': '暂无盘点任务',
    'opname.featureComingSoon': '创建盘点功能即将推出',
    'opname.date': '盘点日期',
    'opname.department': '部门',
    'opname.selectDept': '选择部门',
    'opname.typeRoutine': '例行盘点',
    'opname.typeAnnual': '年度盘点',
    'opname.typeSpot': '抽查',
    'opname.systemQty': '系统数量',
    'opname.physicalQty': '实际数量',
    'opname.varianceQty': '差异',
    'opname.unitCost': '单位成本',
    'opname.varianceValue': '差异金额',
    'opname.loadItems': '加载物品',
    'opname.successSave': '盘点任务已创建',
    'opname.successDelete': '盘点已删除',
    'opname.confirmDelete': '确定删除此盘点任务？',
    'opname.statusDraft': '草稿',
    'opname.statusPending': '待处理',
    'opname.statusCounting': '盘点中',
    'opname.statusSubmitted': '已提交',
    'opname.statusVerified': '已核实',
    'opname.statusApproved': '已批准',
    'opname.statusRejected': '已拒绝',
    'opname.totalVariance': '差异合计',
    'opname.notes': '备注',
    'opname.submit': '提交盘点',
    'opname.verify': '核实',
    'opname.approve': '批准',
    'opname.category': '物品类别',
    'opname.selectCategory': '选择类别',
    'opname.assignedTo': '指派给',
    'opname.selectUser': '选择用户',
    'opname.assignedBy': '指派人',
    'opname.startCounting': '开始盘点',
    'opname.openDetail': '打开详情',
    'opname.submitCounting': '提交盘点结果',
    'opname.confirmStart': '开始盘点此任务？物品将被锁定无法进出。',
    'opname.confirmSubmit': '提交盘点结果待审批？',
    'opname.selectItems': '选择物品',
    'opname.selectAll': '全选',
    'opname.selectedCount': '项已选',
    'opname.noPermission': '仅总经理/财务总监可创建盘点任务',
    'opname.countingStarted': '盘点已开始',
    'opname.countingSubmitted': '盘点已提交待审批',

    // Write-Off
    'writeoff.title': '报废',
    'writeoff.subtitle': '库存报废列表',
    'writeoff.create': '创建报废单',
    'writeoff.number': '报废编号',
    'writeoff.reason': '原因',
    'writeoff.totalValue': '总价值',
    'writeoff.empty': '暂无报废记录',
    'writeoff.featureComingSoon': '创建报废功能即将推出',
    'writeoff.date': '报废日期',
    'writeoff.department': '部门',
    'writeoff.addItem': '添加物品',
    'writeoff.qty': '数量',
    'writeoff.unitCost': '单位成本',
    'writeoff.lineTotal': '合计',
    'writeoff.successSave': '报废单已保存',
    'writeoff.successDelete': '报废单已删除',
    'writeoff.confirmDelete': '确定删除此报废单？',
    'writeoff.statusDraft': '草稿',
    'writeoff.statusPending': '待审批',
    'writeoff.statusApproved': '已批准',
    'writeoff.submit': '提交',
    'writeoff.approve': '批准',
    'writeoff.notes': '备注',
    'writeoff.reasonExpired': '过期',
    'writeoff.reasonDamaged': '损坏',
    'writeoff.reasonLost': '丢失',
    'writeoff.reasonObsolete': '报废',
    'writeoff.reasonOther': '其他',

    // Backdate Control
    'backdate.maxBackdateDays': '最大回溯天数',
    'backdate.gracePeriodDays': '宽限期天数',
    'backdate.periodLocked': '期间已锁定',
    'backdate.dateTooOld': '日期超过最大回溯限制',
    'backdate.periodLocks': '期间锁定',
    'backdate.reopenPeriod': '重新开放期间',
    'backdate.lockPeriod': '锁定期间',
    'backdate.autoLocked': '自动锁定',
    'backdate.manualLocked': '手动锁定',
    'backdate.reopenedBy': '重新开放者',

    // Purchase Invoice
    'pi.title': '采购发票',
    'pi.subtitle': '采购发票列表',
    'pi.create': '创建发票',
    'pi.number': '发票编号',
    'pi.invoiceNumber': '供应商发票号',
    'pi.invoiceDate': '发票日期',
    'pi.dueDate': '到期日',
    'pi.vendor': '供应商',
    'pi.selectVendor': '选择供应商',
    'pi.empty': '暂无采购发票',
    'pi.addItem': '添加物品',
    'pi.unitPrice': '单价',
    'pi.qty': '数量',
    'pi.discount': '折扣 %',
    'pi.tax': '税 %',
    'pi.lineTotal': '行合计',
    'pi.subtotal': '小计',
    'pi.taxAmount': '税额',
    'pi.discountAmount': '折扣额',
    'pi.totalAmount': '总金额',
    'pi.successSave': '采购发票已保存',
    'pi.successDelete': '采购发票已删除',
    'pi.confirmDelete': '确定删除此采购发票？',
    'pi.statusDraft': '草稿',
    'pi.statusPending': '待审批',
    'pi.statusApproved': '已批准',
    'pi.statusPaid': '已付款',
    'pi.statusCancelled': '已取消',
    'pi.paymentStatus': '付款状态',
    'pi.paymentUnpaid': '未付款',
    'pi.paymentPartial': '部分付款',
    'pi.paymentPaid': '已付款',
    'pi.submit': '提交',
    'pi.approve': '批准',
    'pi.reject': '拒绝',
    'pi.markPaid': '标记已付',
    'pi.notes': '备注',
    'pi.fromPO': '来自采购订单',
    'pi.selectPO': '选择采购订单导入',
    'pi.importFromPO': '从采购订单导入',
    'pi.convertSuccess': '采购订单已转为发票',
    'pi.items': '物品',

    // Purchase Received
    'menu.gr': '采购收货',
    'gr.title': '采购收货',
    'gr.subtitle': '从采购发票接收货物',
    'gr.create': '新建收货',
    'gr.number': '收货单号',
    'gr.selectPI': '选择采购发票',
    'gr.receivedDate': '收货日期',
    'gr.fromPI': '来自发票',
    'gr.piQty': '发票数量',
    'gr.receivedQty': '接收数量',
    'gr.prevReceived': '已接收',
    'gr.remaining': '剩余',
    'gr.warehouse': '目标仓库',
    'gr.selectWarehouse': '选择仓库',
    'gr.confirm': '确认收货',
    'gr.successSave': '收货单已保存',
    'gr.successConfirm': '收货已确认，库存已更新',
    'gr.successDelete': '收货单已删除',
    'gr.confirmDelete': '确定删除此收货单？',
    'gr.confirmReceipt': '确认此收货？库存将被更新。',
    'gr.empty': '暂无收货记录',
    'gr.notes': '备注',
    'gr.errorSave': '保存收货单出错',
    'gr.errorOverQty': '接收数量超过发票剩余数量',
    'gr.errorNoWarehouse': '请选择目标仓库',
    'gr.status': '状态',
    'gr.items': '物品',

    // Room Make Up
    'makeup.title': '客房整理',
    'makeup.subtitle': '客房整理管理',
    'makeup.newMakeup': '新建整理',
    'makeup.number': '整理编号',
    'makeup.room': '房间',
    'makeup.selectRoom': '选择房间',
    'makeup.searchPlaceholder': '搜索整理...',
    'makeup.replaceItems': '更换物品',
    'makeup.refillItems': '补充物品',
    'makeup.defaultQty': '默认',
    'makeup.actualQty': '实际',
    'makeup.dirtyQty': '脏污',
    'makeup.warehouse': '仓库',
    'makeup.itemCount': '物品数',
    'makeup.notes': '备注',
    'makeup.notesPlaceholder': '可选备注...',
    'makeup.saveDraft': '保存草稿',
    'makeup.confirm': '确认',
    'makeup.confirmMsg': '确认此客房整理？库存将被更新。',
    'makeup.successSave': '客房整理已保存',
    'makeup.successConfirm': '客房整理已确认，库存已更新',
    'makeup.errorSave': '保存客房整理失败',
    'makeup.lostBreakage': '丢失与损坏',
    'makeup.lbItems': '丢失/损坏物品',
    'makeup.addLBItem': '添加丢失/损坏物品',
    'makeup.lbSelectItem': '选择物品',
    'makeup.lbQty': '数量',
    'makeup.lbReason': '原因',
    'makeup.lbReasonLost': '丢失',
    'makeup.lbReasonDamaged': '损坏',
    'makeup.lbSourceWarehouse': '替换来源',
    'makeup.lbNoItems': '无丢失/损坏物品',
    'makeup.activityChecklist': '活动检查清单',
    'makeup.activityChecklistDesc': '完成状态',
    'makeup.noActivityTemplates': '未配置活动模板',
    'makeup.inuseVerification': '在用物品验证',
    'makeup.inuseVerificationDesc': '库存余额检查',
    'makeup.expectedQty': '预期',
    'makeup.difference': '差异',
    'makeup.noInuseItems': '无在用物品需验证',

    // Transfer
    'transfer.title': '库存调拨',
    'transfer.subtitle': '仓库间调拨',
    'transfer.newTransfer': '新建调拨',
    'transfer.number': '调拨编号',
    'transfer.from': '来源',
    'transfer.to': '目标',
    'transfer.selectWarehouse': '选择仓库',
    'transfer.selectItem': '选择物品',
    'transfer.searchPlaceholder': '搜索调拨...',
    'transfer.items': '调拨物品',
    'transfer.addItem': '添加物品',
    'transfer.notes': '备注',
    'transfer.saveDraft': '保存草稿',
    'transfer.confirm': '确认',
    'transfer.confirmMsg': '确认此调拨？库存将被更新。',
    'transfer.successSave': '调拨已保存',
    'transfer.successConfirm': '调拨已确认，库存已更新',
    'transfer.errorSave': '保存调拨失败',
    'transfer.selectWarehouses': '请选择来源和目标仓库',
    'transfer.sameWarehouse': '来源和目标仓库不能相同',
    'transfer.addItems': '请至少添加一个物品',

    // Direct Purchase
    'dp.title': '直接采购',
    'dp.subtitle': '无供应商直接采购',
    'dp.create': '新建直接采购',
    'dp.number': '直采编号',
    'dp.date': '采购日期',
    'dp.location': '采购地点',
    'dp.locationPlaceholder': '例: 菜市场, 淘宝, 超市',
    'dp.searchPlaceholder': '搜索直接采购...',
    'dp.items': '采购物品',
    'dp.addItem': '添加物品',
    'dp.selectItem': '选择物品',
    'dp.qty': '数量',
    'dp.unitPrice': '单价',
    'dp.totalPrice': '合计',
    'dp.warehouse': '仓库',
    'dp.selectWarehouse': '选择仓库',
    'dp.notes': '备注',
    'dp.saveDraft': '保存草稿',
    'dp.confirm': '确认',
    'dp.confirmMsg': '确认此直接采购？库存将被更新。',
    'dp.successSave': '直接采购已保存',
    'dp.successConfirm': '直接采购已确认，库存已更新',
    'dp.errorSave': '保存直接采购失败',
    'dp.empty': '暂无直接采购记录',
    'dp.confirmDelete': '删除此直接采购？',
    'dp.successDelete': '直接采购已删除',
    'dp.grandTotal': '总计',
    'dp.addItems': '请至少添加一个物品',
    'dp.locationRequired': '请填写采购地点',

    // Single Item Usage
    'menu.singleUsage': '单品使用',
    'siu.title': '单品使用',
    'siu.subtitle': '记录单品使用',
    'siu.create': '记录使用',
    'siu.number': '使用编号',
    'siu.date': '使用日期',
    'siu.item': '物品',
    'siu.selectItem': '选择物品',
    'siu.warehouse': '来源仓库',
    'siu.selectWarehouse': '选择仓库',
    'siu.department': '部门',
    'siu.selectDepartment': '选择部门',
    'siu.qty': '数量',
    'siu.qtyMax1': '最大数量为1',
    'siu.notes': '备注',
    'siu.confirm': '确认使用',
    'siu.confirmMsg': '确认使用？库存将立即减少。',
    'siu.successConfirm': '使用已记录，库存已更新',
    'siu.errorSave': '记录使用失败',
    'siu.empty': '暂无使用记录',
    'siu.searchPlaceholder': '搜索使用记录...',
    'siu.itemRequired': '请选择物品',
    'siu.warehouseRequired': '请选择仓库',
    'siu.departmentRequired': '请选择部门',
    'siu.noStock': '所选仓库库存不足',
    'siu.usedBy': '使用人',

    // In-Use Warehouse
    'menu.inUseWarehouse': '在用仓库',
    'iu.title': '在用仓库',
    'iu.subtitle': '跟踪当前在用的可重复使用物品',
    'iu.filterCategory': '按类别筛选',
    'iu.allCategories': '所有类别',
    'iu.item': '物品',
    'iu.category': '类别',
    'iu.qty': '数量',
    'iu.status': '状态',
    'iu.inUse': '使用中',
    'iu.markDepleted': '标记耗尽',
    'iu.depletedConfirm': '标记此物品为耗尽？库存将从在用仓库中移除。',
    'iu.depletedSuccess': '物品已标记为耗尽',
    'iu.depletedError': '标记物品耗尽失败',
    'iu.empty': '当前没有在用物品',
    'iu.searchPlaceholder': '搜索在用物品...',
    'iu.lastUpdated': '最后更新',
    'iu.warehouse': '在用仓库',

    // Approval
    'approval.approvedBy': '批准人',
    'approval.approvedAt': '批准时间',
    'approval.rejectedBy': '拒绝人',
    'approval.rejectedAt': '拒绝时间',
    'approval.info': '审批信息',
    'approval.confirmApprove': '确认批准此文档？',
    'approval.confirmReject': '确认拒绝此文档？',
    'approval.notApproved': '尚未批准',
    'approval.pageTitle': '审批中心',
    'approval.pageSubtitle': '审核待审批文档',
    'approval.pending': '待审批',
    'approval.history': '历史',
    'approval.noPending': '没有待审批项目',
    'approval.approve': '批准',
    'approval.reject': '拒绝',
    'approval.rejectReason': '拒绝原因',
    'approval.gmApproved': 'GM已批准',
    'approval.findirApproved': '财务总监已批准',
    'approval.waitingGM': '等待GM',
    'approval.waitingFinDir': '等待财务总监',
    'approval.waitingBoth': '等待GM和财务总监',
    'approval.submittedBy': '提交人',
    'approval.submittedAt': '提交时间',
    'menu.approval': '审批',

    // Reports
    'reports.title': '报表',
    'reports.subtitle': '库存摘要与分析',
    'reports.totalStockValue': '库存总价值',
    'reports.totalSKU': 'SKU总数',
    'reports.hotel': '酒店',
    'reports.valuationReport': '库存估值报告',
    'reports.selectReport': '选择报表',
    'reports.stockValuation': '库存估值',
    'reports.stockMovement': '库存变动',
    'reports.purchaseSummary': '采购汇总',
    'reports.lowStock': '低库存预警',
    'reports.opnameSummary': '盘点汇总',
    'reports.filterCategory': '类别',
    'reports.filterDept': '部门',
    'reports.filterDateFrom': '开始日期',
    'reports.filterDateTo': '结束日期',
    'reports.allCategories': '所有类别',
    'reports.allDepts': '所有部门',
    'reports.generate': '生成',
    'reports.exportPDF': '导出PDF',
    'reports.exportExcel': '导出Excel',
    'reports.noData': '该报表无数据，请调整筛选条件后重试。',
    'reports.movementType': '类型',
    'reports.movementQty': '数量',
    'reports.reference': '参考号',
    'reports.poNumber': '采购订单号',
    'reports.piNumber': '发票号',
    'reports.vendorName': '供应商',
    'reports.totalPO': '采购订单总数',
    'reports.totalPI': '发票总数',
    'reports.totalPOValue': '采购订单总额',
    'reports.totalPIValue': '发票总额',
    'reports.minStock': '最低库存',
    'reports.currentStock': '当前库存',
    'reports.shortage': '缺口',
    'reports.opnameNumber': '盘点编号',
    'reports.varianceValue': '差异金额',

    // Opening Balance
    // Opening Balance
    'ob.title': '期初余额',
    'ob.subtitle': '按类别进行初始库存盘点',
    'ob.menu': '期初余额',
    'ob.selectCategory': '选择类别开始盘点',
    'ob.itemCode': '物品编码',
    'ob.itemName': '物品名称',
    'ob.unit': '单位',
    'ob.category': '类别',
    'ob.qtyOnHand': '库存数量',
    'ob.unitCost': '单位成本（Rp）',
    'ob.totalValue': '总价值',
    'ob.totalQty': '总数量',
    'ob.save': '保存',
    'ob.saving': '保存中...',
    'ob.successSave': '期初余额保存成功',
    'ob.errorSave': '保存时出错',
    'ob.noItems': '该类别暂无物品。',
    'ob.totalItems': '物品总数',
    'ob.itemsCounted': '已盘点物品',
    'ob.totalStockValue': '库存总价值',
    'ob.locked': '已锁定',
    'ob.lockWarning': '锁定后，该类别将无法修改。请确保所有数据正确。',
    'ob.lockConfirm': '确定要锁定该类别吗？此操作无法撤销。',
    'ob.lockBtn': '锁定类别',
    'ob.unlocked': '草稿',
    'ob.lockedStatus': '已锁定',
    'ob.searchPlaceholder': '搜索物品...',
    'ob.backToCategories': '返回类别列表',
    'ob.progress': '进度',
    'ob.items': '项',
    'ob.allCategories': '全部类别',
    'ob.categoriesLocked': '已锁定类别',
    'ob.draft': '草稿',
    'ob.completed': '已完成',
    'ob.startCounting': '开始盘点',
    'ob.continue': '继续',
    'ob.view': '查看',
    'ob.inStock': '库存',
    'ob.inUse': '使用中',
    'ob.dirty': '待洗',
    'ob.inLaundry': '送洗中',
    'ob.damaged': '损坏',
    'ob.totalPcs': '总件数',
    // Fixed Asset statuses
    'ob.good': '良好',
    'ob.fair': '一般',
    'ob.poor': '较差',
    // Machinery statuses
    'ob.operational': '运行中',
    'ob.maintenance': '维护中',
    'ob.broken': '故障/停用',

    // Users
    'users.title': '用户管理',
    'users.subtitle': '创建和管理用户',
    'users.users': '用户',
    'users.fullName': '姓名',
    'users.username': '用户名',
    'users.role': '角色',
    'users.hotel': '酒店',
    'users.email': '邮箱',
    'users.phone': '电话',
    'users.department': '部门',
    'users.createUser': '创建用户',
    'users.editUser': '编辑用户',
    'users.selectRole': '选择角色',
    'users.selectHotel': '选择酒店',
    'users.selectDept': '选择部门',
    'users.allHotels': '所有酒店（集团）',
    'users.successSave': '用户保存成功',
    'users.successDelete': '用户删除成功',
    'users.confirmDelete': '确定删除该用户？',
    'users.password': '密码',
    'users.passwordHint': '最少6个字符（留空保持不变）',

    // Role Management
    'roles.title': '角色管理',
    'roles.subtitle': '定义每个角色的访问权限',
    'roles.roles': '角色',
    'roles.createRole': '创建角色',
    'roles.editRole': '编辑角色',
    'roles.roleName': '角色名称',
    'roles.description': '描述',
    'roles.system': '系统',
    'roles.menuAccess': '菜单访问',
    'roles.specialActions': '特殊操作',
    'roles.successSave': '角色保存成功',
    'roles.successDelete': '角色删除成功',
    'roles.confirmDelete': '确定删除该角色？',
    'roles.cannotDeleteSystem': '无法删除系统角色',
    'roles.permissions': '权限',
    'roles.action.approve_pr': '审批PR',
    'roles.action.approve_po': '审批PO',
    'roles.action.approve_pi': '审批发票',
    'roles.action.approve_wo': '审批报废',
    'roles.action.approve_opname': '审批盘点',
    'roles.action.revoke_approval': '撤销批准',
    'roles.action.revert_to_draft': '恢复为草稿',
    'roles.action.export_reports': '导出报表',
    'roles.action.manage_users': '管理用户',
    'roles.action.manage_roles': '管理角色',
    'roles.action.unlock_opening_balance': '解锁期初余额',
    'roles.action.view_all_room_makeups': '查看所有客房整理单',

    // System Settings
    'settings.title': '系统设置',
    'settings.subtitle': '配置全系统偏好设置',
    'settings.timezone': '时区',
    'settings.timezoneDesc': '所有日期/时间显示使用的时区',
    'settings.currency': '货币',
    'settings.currencyDesc': '财务数据的默认货币',
    'settings.dateFormat': '日期格式',
    'settings.dateFormatDesc': '系统中日期的显示格式',
    'settings.language': '默认语言',
    'settings.languageDesc': '新用户的默认界面语言',
    'settings.lowStockThreshold': '低库存阈值',
    'settings.lowStockThresholdDesc': '低库存警报的默认阈值',
    'settings.autoGenerateCode': '自动生成编码',
    'settings.autoGenerateCodeDesc': '自动生成物品/文档编码',
    'settings.fiscalYearStart': '财年起始月份',
    'settings.fiscalYearStartDesc': '财年的起始月份',
    'settings.saved': '设置保存成功',
    'settings.saveError': '保存设置失败',
    'settings.save': '保存设置',
    'settings.saving': '保存中...',
    'settings.general': '常规',
    'settings.inventory': '库存',
    'settings.regional': '区域',
    'settings.maintenance': '维护',
    'settings.maintenanceMode': '维护模式',
    'settings.maintenanceModeDesc': '启用后，除超级管理员和授权角色外的所有用户将被注销并阻止访问系统。',
    'settings.maintenanceOn': '维护中',
    'settings.maintenanceOff': '正常运行',
    'settings.maintenanceWarning': '启用维护模式将立即踢出所有未授权用户。请在激活前通知您的团队。',
    'settings.maintenanceActive': '维护模式当前已激活。只有超级管理员和拥有维护访问权限的角色可以使用系统。',
    'roles.allowMaintenanceAccess': '允许维护访问',
    'roles.allowMaintenanceAccessDesc': '拥有此角色的用户在维护模式下仍可访问系统',
    'menu.systemSettings': '系统设置',
    'menu.cronJobs': '定时任务',

    // Change Password
    'pwd.title': '修改密码',
    'pwd.subtitle': '更新您的账户密码',
    'pwd.currentPassword': '当前密码',
    'pwd.newPassword': '新密码',
    'pwd.confirmPassword': '确认新密码',
    'pwd.change': '修改密码',
    'pwd.success': '密码修改成功',
    'pwd.errorMismatch': '两次输入的密码不一致',
    'pwd.errorShort': '密码至少需要6个字符',
    'pwd.errorCurrent': '当前密码不正确',
    'pwd.selectUser': '选择用户',
  }
};

/**
 * LanguageProvider component - manages language state and translation
 */
export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('inventory_lang') || 'en');

  /**
   * Translate a key to current language, fallback to English then key
   */
  function t(key) {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }

  /**
   * Toggle between English and Chinese
   */
  function toggleLanguage() {
    const newLang = lang === 'en' ? 'zh' : 'en';
    setLang(newLang);
    localStorage.setItem('inventory_lang', newLang);
    document.documentElement.lang = newLang;
  }

  /**
   * Update document language when language changes
   */
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}
